### ISSUE TITLE
store chat api key

### ISSUE THREAD

**Issue by seanmakesgames** [DrizzlyBear/hackmud_chat_web#10]
refreshing the page causes it to not work anymore.

**Comment by ethankaminski** [comment]
Are you running it from a `file:` URL? If so, won't work - browser-level security reasons. I suggest running it over localhost (which worked for me just now).

**Comment by seanmakesgames** [comment]
ah totes. makes sense. and yes running from file: url
I'll add it to the website and try it from there. Also will probably break up the code a bit so in-place replace will work better when I migrate it into the main website codebase.

**Comment by ethankaminski** [comment]
Yep, feel free to break it up a bit. What I'm doing is `python -m SimpleHTTPServer`, IIRC; but hosting it on the website also works.

**Comment by seanmakesgames** [comment]
that's where it's planned to be anyhow -- and my local dev instance has a server attached as well with https, etc. so bonus.
