### ISSUE TITLE
losing internet connection causes polls to continue to fail

### ISSUE THREAD

**Issue by seanmakesgames** [DrizzlyBear/hackmud_chat_web#11]
closed laptop, when reopened - polling stopped

**Comment by KuroTsuto** [comment]
I've tried emulating this with Chrome's "offline" toggle in the Devtools Network tab, but I can't reproduce it
![screenshot_11](https://cloud.githubusercontent.com/assets/372884/26023901/58c70d6e-377b-11e7-9fdf-fb90e98c8558.png)

**Comment by seanmakesgames** [comment]
I'll try for another repro as well. (this could have easily have been fixed by some other checkin since)

**Comment by seanmakesgames** [comment]
Yeah, no repro. closing. :)

**Comment by KuroTsuto** [comment]
No news is good news \o/
