### ISSUE TITLE
Implement tells

### ISSUE THREAD

**Issue by ethankaminski** [DrizzlyBear/hackmud_chat_web#12]
Make it so `chats.tell` messages can be viewed and sent.

**Comment by hackmud-dtr** [comment]
@seanmakesgames This can probably get closed now

**Comment by seanmakesgames** [comment]
Nice. In the future you can add [closes #12] to your commits or your PR title (I think) and that'll autoclose

**Comment by hackmud-dtr** [comment]
Oh nice.
