### ISSUE TITLE
Automatically hyperlink URLs

### ISSUE THREAD

**Issue by ethankaminski** [DrizzlyBear/hackmud_chat_web#62]

**Comment by hackmud-dtr** [comment]
Security issue?

**Comment by seanmakesgames** [comment]
maybe, but... we could do domain checking for whitelisted domains

**Comment by ethankaminski** [comment]
That could be a bit of a headache. Personally, I'm not inclined to come up with a whitelist from scratch; but if someone else provides me with a whitelist, I would be willing to check it over and (if I have time to) also use it.

**Comment by KuroTsuto** [comment]
In-game URLs are already subject to the discretion of the end-user - how about a disable-able modal warning that you may be navigating to a potentially malicious 3rd-party site, similar to how Discord addresses links?

**Comment by seanmakesgames** [comment]
I was actually talking about a merger of your two ideas, where whitelisted stuff would not need to prompt about going elsewhere, but otherwise it would still linkify, but give you a notification.

**Comment by seanmakesgames** [comment]
For v1 impl of this, let's just auto-hyperlink hackmud.com urls.

**Comment by NGTmeaty** [comment]
A discord approach could be cool. Prompt the user and tell them exactly where it's going to avoid confusion.

**Comment by seanmakesgames** [comment]
forgot a fixes #62 in my checkin
3f10a48c77040ec9ddd2b574f5bd8ddbca530843
