### ISSUE TITLE
Pollrate too fast for server?

### ISSUE THREAD

**Issue by KuroTsuto** [DrizzlyBear/hackmud_chat_web#64]
Currently, the base 1200ms pollrate results in a large number of HTTP 429 responses for me:

![screenshot_10](https://cloud.githubusercontent.com/assets/372884/26018671/1ecb5b84-3725-11e7-9d88-3f67e6fd4798.png)

What is the server's permitted minimum polling interval?

If it is 1200ms (or less), I wonder if using `setTimeout()` in the poll callback instead of `setInterval()` around the poll request might alleviate the issue. Polling requests could be `Promise.race()`d against a larger "max time without poll" timeout to ensure that unusually long or lost requests don't unnecessarily lengthen the poll interval.

Alternately, the base polling interval could be increased in small increments based on the frequency of 429s. If the server is modified to add a `Retry-After` header to 429s, the base polling interval could be adjusted based on that.

**Comment by KuroTsuto** [comment]
I can no longer reproduce this issue.

**Comment by seanmakesgames** [comment]
I mean, this is still possible-- if your burst exceeds 1200, or if you have multiple chat tabs open (the latter is the more likely)
