### ISSUE TITLE
[Server-Side] Issue new token for new chat pass

### ISSUE THREAD

**Issue by KuroTsuto** [DrizzlyBear/hackmud_chat_web#74]
Currently sending a new chat_pass to the server produces the old chat token, presumably until that token naturally expires. Given that tokens are used in various custom chat clients, and additionally have the potential to end up stored in the cookies of public computers, it would be great if new chat passes always resulted in a new token and invalidated the old one.

I was recently helping someone debug an out-of-game bot which relied on the chat API as it's source for in-game data - on a couple occasions code was exchanged over hastebin without the token being properly scrubbed, and at one point we started running into rate-limiting responses from the chat API. In all likelihood we overlooked an API client somewhere, but it's possible that the token fell into malicious hands. Unable to obtain a new chat token, the other party was unable to invalidate whatever client was responsible for the error.

**Comment by seanmakesgames** [comment]
Currently there is only one token active at a time. This will be changing in the future. 
`chat_revoke_tokens` with a following `chat_pass` call should get you what you need from this in the interim.

**Comment by KuroTsuto** [comment]
Ah excellent - thank you very much, sean!
