### ISSUE TITLE
Font in repo is not font used

### ISSUE THREAD

**Issue by hackmud-dtr** [DrizzlyBear/hackmud_chat_web#83]
The font in the repo appears to be a mostly vanilla copy of White Rabbit, without the italic {}, corruption characters, or other tweaks. The actual font used on the website appears to be the game font, and it would be nice to have the tweaks in that copy available under the MIT license for use on other things. Copying the font used into this repo gets it covered by MIT.

**Comment by seanmakesgames** [comment]
I'm actually not seeing this. I downloaded the ttf directly out of the repo, and it's up to date

**Comment by hackmud-dtr** [comment]
Weird; the font in the repo (with no changes) looks good, but a thing I used said font for still shows straight {}. Replaced with a fresh download (and git claims 0 diffs over the old ones) and works. I have no idea.

**Comment by hackmud-dtr** [comment]
Oh I see, the CSS was wrong and it was a font fallback thing. That makes more sense

**Comment by seanmakesgames** [comment]
thanks for taking a look at it. :)
