### ISSUE TITLE
Would be rad to have some continuous integration. 

### ISSUE THREAD

**Issue by seanmakesgames** [DrizzlyBear/hackmud_chat_web#88]
If anyone is interested in exploring that, I would love to see it in here.

**Comment by KuroTsuto** [comment]
I would love this!

I haven't worked much with CI, but I feel like the codebase currently isn't all that modular; it might make good tests pretty difficult to write?

**Comment by seanmakesgames** [comment]
nah, let's go for it. We can start with small tests to begin with. Just get it integrated with some simple ones.
