### ISSUE TITLE
Add hover 'title' to timestamps to give out full timestamp

### ISSUE THREAD

**Issue by seanmakesgames** [DrizzlyBear/hackmud_chat_web#90]
I want to see what day chats were from. Maybe include something like relative time in there as well. (x days ago) or whatever

**Comment by hackmud-dtr** [comment]
Can we get this in game too plz? ;p

But uh, I can easily add a game timestr format on hover.

**Comment by seanmakesgames** [comment]
thanks. in-game is a bit harder, but I'm sure I'll be doing a bit of a think on it design wise.
