### ISSUE TITLE
message scrollback

### ISSUE THREAD

**Issue by seanmakesgames** [DrizzlyBear/hackmud_chat_web#91]
on all channels / tells

**Comment by hackmud-dtr** [comment]
This requires working chat_history endpoint (see bug on forums); it isn't really viable to implement this without it.

forum bug report on chat_history: https://www.hackmud.com/forums/bugs_features_ideas/chat_api_chat_history_returns_empty_array_if_you_did_not_join_leave_the_specified_channel_between_the_specified_times

**Comment by hackmud-dtr** [comment]
What the chat history bug means in practice is that chat_history is almost never usable outside of a testing environment where you just recently joined a test channel. For users passively in 0000 for long periods of time (a common case), chat_history is useless.

**Comment by seanmakesgames** [comment]
yep. totes understood. we'll get it sorted.

**Comment by seanmakesgames** [comment]
fixed by https://github.com/DrizzlyBear/hackmud_chat_web/commit/e66bc2ce262959096de8a3deab77fa7449e8c109
